/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fintx;

import java.util.concurrent.Callable;
import picocli.CommandLine;

@CommandLine.Command
public class App implements Callable<Integer> {

    public static void main(String[] args) {
        new CommandLine(new App()).execute(args);
    }

    @Override
    public Integer call() {
        System.out.println("Hello World!");
        return 0;
    }
}
